[package]
name = "ext-php-rs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ext-php-rs = "0.7"
lazy_static = "1.4"

[lib]
crate-type = ["cdylib"]